stages:
    - test
    - deploy

test:
    image: node:12.13
    stage: test
    variables:
        DB_CONNECTION_TEST: 'mongodb+srv://Choi-R:Gembel123.@cluster0-iamk7.mongodb.net/road-to-be-rich?retryWrites=true&w=majority'
    services: 
        - mongo:latest
    script:
        - echo $DB_CONNECTION_TEST
        - npm install
        - npm test
    only:
        - development
deploy:
    image: ruby:2.5.6
    stage: deploy
    script:
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl
        - dpl --provider=heroku --app=$HEROKU_APPNAME --api-key=$HEROKU_APIKEY
    only:
        - development